### ISSUE TITLE
Why did you remove the input coordinates in EGNN?

### ISSUE THREAD

**Issue by Layne-Huang** [ehoogeboom/e3_diffusion_for_molecules#4]
I am sorry to bother you. Why did you remove the input coordinates in EGNN and why didn't you do the same operation for the atom features or in GNN?

**Comment by ehoogeboom** [comment]
No worries :). In the EGNN, the x behaves like a position. This means that:
Under an action of rotation R and translation t, the position rotates and translates, so Rx + t. 

But, sometimes we want to have stuff that behaves like a velocity. This means that:
Under an action of rotation R and translation t, the velocity _only_ rotates, so Rv. (This is because it is always assumed to be starting from x. It may be useful to look at Figure 1 from the EGNN paper here https://arxiv.org/pdf/2102.09844.pdf).  

The denoising we want to predict should behave like a velocity, and when we subtract the input x from the output x_L, we get something that behaves like a velocity. Suppose we look at our output x_L - x. Under the action of rotation and translation it is:
(Rx_L + t) - (Rx + t) = R(x_L - x), so the translation t has cancelled out and it behaves like a velocity as desired.

For atom features it is not necessary as they are not affected by (they are invariant to) actions of rotation or translation.
