### ISSUE TITLE
Question about the units of gap, homo and lumo in conditional gneration task

### ISSUE THREAD

**Issue by Layne-Huang** [ehoogeboom/e3_diffusion_for_molecules#9]
Hi,

I have noticed that the units of gap, homo and lumo in table 3 are meV. Is this a typo error? I think it should be ev or ha.
Besides, the l1 losses of the three properties are too large. Could you please check it?

Thank you very much!

**Comment by vgsatorras** [comment]
Hi Layne,

The units in Table 3 are meV. This is not a typo. In the code they are in eV. We conversed them from eV to meV when reporting the results in the paper for better readability and to be consistent with previous works.

> Besides, the l1 losses of the three properties are too large. Could you please check it?

The numbers reported in the paper for those three metrics should be 1000 times larger than the numbers obtained when running the code because of the conversion from eV to meV. 

Best,
Victor
